repos:
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3.9
        args: [".", "-l", "80", "-t", "py39", "--exclude", "/(\\.vscode)/"]